---
title: "Lattice"
output: html_notebook
---
```{r}
library(lattice)
```
Boxplot
```{r}
bwplot(trees$Volume, main = "Árvores", xlab = "Volume")
```
Histograma
```{r}
#aspect é a proporção, type: percent/count/density, nint é o número de quebras
histogram(trees$Volume, main = "Árvores", xlab = "Volume", aspect = 1, type = "percent", nint = 20)
```
Histograma condicional
```{r}
#peso das galinhas de acordo com alimentação
chickwts
#histograma
histogram(chickwts$weight)
#agregando dados
aggregate(chickwts$weight, by = list(chickwts$feed), FUN = sum)
#histograma condicional
histogram(~weight | feed, data = chickwts)
```
Gráfico de dispersão condicional
```{r}
#CO2, conc: concentração de co2, uptake: captação de co2
CO2
xyplot(CO2$conc ~ CO2$uptake)
#type é a origem
xyplot(CO2$conc ~ CO2$uptake | CO2$Type)
#refrigerado ou não
xyplot(CO2$conc ~ CO2$uptake | CO2$Treatment)
```
```{r}
#câncer de esôfago
#agegp: idade, alcgp: alcool, tobgp: tabaco
esoph
dotplot(esoph$alcgp ~ esoph$ncontrols, data = esoph)
dotplot(esoph$alcgp ~ esoph$ncontrols | esoph$tobgp)
```
Matriz de dispersão
```{r}
splom(~CO2[4:5] | CO2$Type, CO2)
```
Densidade condicional
```{r}
densityplot(CO2$conc)
densityplot(~CO2$conc | CO2$Treatment)
densityplot(~CO2$conc | CO2$Treatment, plot.points = FALSE)
```
Gráfico 3D
```{r}
#spray para repelir abelhas
OrchardSprays
cloud(decrease ~ rowpos * colpos, data = OrchardSprays)
cloud(decrease ~ rowpos * colpos, groups = treatment, data = OrchardSprays)

```
Level plot
```{r}
trees
levelplot(Girth ~ Height * Volume, data = trees)
```